lst=list(map(int,input("Enter values: ").split()))
print(lst)
print("Size of List:",len(lst))
print("Reversed printed List :\n",lst[::-1])
sort_lst=sorted(lst)
print("Sorted list : \n",sort_lst)
sort_lst=sorted(lst,reverse=True)
print("Reversed Sorted list : \n",sort_lst)
lst.append(118)
print("List after appending element at the end of list \n",lst)
lst.insert(2,79)
print("List after appending element at the particular index of list \n",lst)
